import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Sparkles, TrendingUp, AlertCircle, CheckCircle2, ArrowRight, Code2, Award, Cpu } from 'lucide-react';
import Sidebar from '../components/common/Sidebar';
import TopBar from '../components/common/TopBar';

export default function AiInsightsPage() {
  const insights = [
    {
      title: 'Strong Backend Foundation',
      desc: 'Your Java, Spring Boot, and Node.js proficiency ranks in the top 10% of candidates.',
      priority: 'Strength',
      badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
      icon: CheckCircle2,
      action: 'View Skill Breakdown',
      link: '/skill-proficiency'
    },
    {
      title: 'Improve Machine Learning Proficiency',
      desc: 'Adding PyTorch or TensorFlow skills will increase your match score for 4 target AI projects.',
      priority: 'High Priority',
      badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
      icon: AlertCircle,
      action: 'View Learning Roadmap',
      link: '/skill-gap'
    },
    {
      title: 'Profile is 92% Complete',
      desc: 'Your profile has verified certifications and skills. Add a portfolio link to reach 100%.',
      priority: 'Completion',
      badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
      icon: Award,
      action: 'Edit Profile',
      link: '/profile'
    },
    {
      title: 'Eligible for 8 Hackathon Projects',
      desc: 'Your extracted skill set matches requirements across 8 active platform projects.',
      priority: 'Opportunity',
      badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
      icon: TrendingUp,
      action: 'Browse Projects',
      link: '/projects'
    },
    {
      title: 'Increase GitHub Commit Activity',
      desc: 'Connecting public GitHub repositories boosts your AI resume verification score by +8 points.',
      priority: 'Recommendation',
      badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
      icon: Code2,
      action: 'Connect GitHub',
      link: '/settings'
    }
  ];

  return (
    <div className="flex h-screen bg-slate-950 text-slate-100 overflow-hidden">
      <Sidebar />

      <div className="flex-1 flex flex-col min-w-0 overflow-y-auto">
        <TopBar title="AI Career & Team Insights" />

        <main className="p-6 max-w-7xl mx-auto w-full space-y-6">
          
          {/* Header Banner */}
          <div className="p-6 rounded-3xl glass-card border border-indigo-500/30 bg-gradient-to-r from-slate-900 via-indigo-950/40 to-slate-900 flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-2xl">
            <div>
              <div className="flex items-center gap-2 text-xs font-semibold text-indigo-400 uppercase tracking-widest">
                <Sparkles className="w-4 h-4 text-cyan-400 animate-spin" /> Continuous RAG Diagnostics
              </div>
              <h2 className="text-2xl font-extrabold text-white mt-1">AI Smart Recommendations</h2>
              <p className="text-xs text-slate-300">
                Personalized advice generated by evaluating your resume against current project demand.
              </p>
            </div>
          </div>

          {/* Insights Cards Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {insights.map((item, idx) => {
              const Icon = item.icon;
              return (
                <motion.div
                  key={item.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.1 }}
                  className="p-6 rounded-3xl glass-card glass-card-hover border-white/15 bg-slate-900/80 flex flex-col justify-between space-y-4"
                >
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full border ${item.badgeColor}`}>
                        {item.priority}
                      </span>
                      <Icon className="w-5 h-5 text-indigo-400" />
                    </div>

                    <h3 className="text-base font-bold text-white">{item.title}</h3>
                    <p className="text-xs text-slate-300 leading-relaxed">{item.desc}</p>
                  </div>

                  <div className="pt-3 border-t border-white/10 flex justify-end">
                    <Link
                      to={item.link}
                      className="gradient-btn px-4 py-2 rounded-xl text-xs font-bold text-white flex items-center gap-2"
                    >
                      {item.action} <ArrowRight className="w-3.5 h-3.5" />
                    </Link>
                  </div>
                </motion.div>
              );
            })}
          </div>

        </main>
      </div>
    </div>
  );
}
